#!/bin/sh
#
# Start wcdma 3G....
#

case "$1" in
  start)
 	echo "Starting WCDMA 3G..."
	
	sh /etc/ppp/pppdstart.sh&
	#/sbin/pppd call gprs > /etc/ppp/login.log  &
	;;
  stop)
	echo "Stop WCDMA 3G..."
	sh /etc/ppp/pppdstop.sh&

	;;
  restart|reload)
	"$0" stop
        "$0" start


	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

