#!/bin/sh
#
# Start mdev....
#


case "$1" in
  start)
	echo "Starting mdev..."
	mount -n -o mode=0755 -t tmpfs mdev /dev
	mkdir /dev/pts
	mkdir /dev/shm
        mount -n -t devpts devpts /dev/pts
	mount -t sysfs sysfs /sys

	echo /sbin/mdev > /proc/sys/kernel/hotplug
	/sbin/mdev -s
    echo "Starting mdev OK"
	watchdog -t 1 -T 3 /dev/watchdog

	insmod /root/8188eu.ko
	insmod /root/8192cu.ko
	
	echo "Check updating" 

	################≈–∂œ/opt/hiktsc300-update.tar.gz «∑Ò¥Ê‘⁄######################
	if [ -f "/opt/hiktsc300-update.tar.gz" ];  then
		echo "hiktsc300-update.tar.gz existed,updating..."
		cd /opt
		tar -zxvf hiktsc300-update.tar.gz
		sleep 10
		cd hiktsc300-update
		sh update.sh
		sleep 5
		rm -rf /opt/hiktsc300-update.tar.gz
	else 
		echo "No need to update!"
	fi
	echo "Update check finished!"

	if [ -f "/root/io.ko" ];then
		insmod /root/io.ko
#		test -x /root/hikTSC300 && /root/hikTSC300 &
		test -x /root/hikTSC && /root/hikTSC &
	fi

	vsftpd&
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
